name: Update contributed repos in README

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # every Monday 00:00 UTC — adjust as you like

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build contributed repos list (last 12 months)
        env:
          GH_LOGIN: ${{ github.repository_owner }}
          # Use CONTRIBS_TOKEN if you want to include private repos (see notes below),
          # otherwise the default GITHUB_TOKEN is fine for public contributions.
          GH_TOKEN: ${{ secrets.CONTRIBS_TOKEN || github.token }}
        run: |
          set -euo pipefail

          FROM_DATE="$(date -u -d '1 year ago' +%Y-%m-%dT%H:%M:%SZ)"
          TO_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

          # GraphQL: repositories you've contributed to (commits, PRs, issues, repo)
          # Note: first: 100 per page; most users will fit — you can add pagination if needed.
          PAGE_SIZE=100

          read -r -d '' QUERY <<'GRAPHQL'
          query($login:String!, $from:DateTime!, $to:DateTime!, $first:Int!, $after:String) {
            user(login:$login) {
              contributionsCollection(from:$from, to:$to) {
                repositoriesContributedTo(
                  first:$first,
                  after:$after,
                  includeUserRepositories:false,
                  contributionTypes:[COMMIT, PULL_REQUEST, ISSUE, REPOSITORY]
                ) {
                  nodes {
                    nameWithOwner
                    url
                    isPrivate
                  }
                  pageInfo {
                    hasNextPage
                    endCursor
                  }
                }
              }
            }
          }
          GRAPHQL

          AFTER=null
          > contributed_repos_raw.json
          while : ; do
            RESP=$(jq -n --arg q "$QUERY" \
                        --arg login "$GH_LOGIN" \
                        --arg from "$FROM_DATE" \
                        --arg to "$TO_DATE" \
                        --argjson first "$PAGE_SIZE" \
                        --argjson after "$AFTER" \
                        '{query:$q, variables:{login:$login, from:$from, to:$to, first:$first, after:$after}}' \
                  | curl -sSf -H "Authorization: bearer $GH_TOKEN" \
                              -H "Content-Type: application/json" \
                              -X POST https://api.github.com/graphql \
                              -d @-)

            # Append nodes
            echo "$RESP" | jq '.data.user.contributionsCollection.repositoriesContributedTo.nodes[]' >> contributed_repos_raw.json

            HAS_NEXT=$(echo "$RESP" | jq -r '.data.user.contributionsCollection.repositoriesContributedTo.pageInfo.hasNextPage')
            if [ "$HAS_NEXT" != "true" ]; then
              break
            fi
            AFTER=$(echo "$RESP" | jq -r '.data.user.contributionsCollection.repositoriesContributedTo.pageInfo.endCursor' | jq -R)
          done

          # Build Markdown list (public by default; include private if you want)
          # Set INCLUDE_PRIVATE=true to show private repos (only if your token can see them).
          INCLUDE_PRIVATE=${INCLUDE_PRIVATE:-false}

          if [ "$INCLUDE_PRIVATE" = "true" ]; then
            JQ_FILTER='.'
          else
            JQ_FILTER='select(.isPrivate|not)'
          fi

          jq -s "[ .[] | $JQ_FILTER | {nameWithOwner, url} ] 
                 | unique_by(.nameWithOwner)
                 | sort_by(.nameWithOwner)" contributed_repos_raw.json > contributed_repos.json

          # Limit the list if you want (e.g., top 30)
          LIMIT=${LIMIT:-30}
          jq -r ".[0:$LIMIT] | map(\"- [\(.nameWithOwner)](\(.url))\") | .[]" contributed_repos.json > contributed_repos.md

          # Fallback if empty
          if [ ! -s contributed_repos.md ]; then
            echo "- No public contributions found in the last 12 months." > contributed_repos.md
          fi

      - name: Update README between markers
        run: |
          awk 'BEGIN{p=1}
               /<!-- CONTRIBUTED_REPOS:START -->/{print;print "";system("cat contributed_repos.md");p=0;next}
               /<!-- CONTRIBUTED_REPOS:END -->/{p=1}
               p' README.md > README.new
          mv README.new README.md

      - name: Commit & push
        run: |
          if ! git diff --quiet; then
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git add README.md contributed_repos*.json contributed_repos.md
            git commit -m "chore: update contributed repos section"
            git push
          fi